
version: '3.8'


services:
  semantic-analyzer-api:
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: semantic-analyzer-api
    ports:
      - "5000:5000"
    environment:
      - RATELIMIT_STORAGE_URI=memcached://memcached:11211
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - logs:/usr/src/app/logs
    restart: unless-stopped
    depends_on:
      - memcached
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s 
      timeout: 10s   
      retries: 3       
      start_period: 40s


  memcached:
    image: memcached:1.6-alpine 
    container_name: semantic-analyzer-memcached
    restart: unless-stopped #


volumes:
  logs:
    driver: local 
