version: '3.8'

services:
  semantic-question-analyzer:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - MEMCACHED_URL=memcached://memcached:11211
    depends_on:
      - memcached

  memcached:
    image: memcached:latest
    
